import Proof.Packets.CyclePaletteReserveStage3

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

def slots4 : Fin 3→Fin 80 := ![1,48,49]
theorem injective4 : Function.Injective slots4 := by decide
def phase4 := RecoveryFocus.machine slots4 worker4
def bank4 (B w : Nat) := install slots4 (bank3 B w) (output4 B w)
theorem bank4_slot (B w : Nat) (j : Fin 3) : bank4 B w (slots4 j)=output4 B w j :=
  install_slot slots4 injective4 _ _ j
theorem bank4_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots4 j≠i) : bank4 B w i=bank3 B w i :=
  install_other slots4 _ _ _ hi

theorem input4_join (B w : Nat) : ∀ j,bank3 B w (slots4 j)=input4 B w j := by
  intro j
  fin_cases j
  · change bank3 B w 1=input4 B w 0
    rw [bank3_other B w 1 (by decide)]
    rw [bank2_other B w 1 (by decide)]
    rw [bank1_other B w 1 (by decide)]
    exact (CycleLiveSuccessor.source_eq w).symm
  · change bank3 B w 48=input4 B w 1
    rw [bank3_other B w 48 (by decide)]
    rw [bank2_other B w 48 (by decide)]
    rw [bank1_other B w 48 (by decide)]
    rfl
  · change bank3 B w 49=input4 B w 2
    rw [bank3_other B w 49 (by decide)]
    rw [bank2_other B w 49 (by decide)]
    rw [bank1_other B w 49 (by decide)]
    rfl
theorem step4 (B w : Nat) : Step phase4 (cost4 B w) (fun _=>0) (bank3 B w)
    (fun _=>0) (bank4 B w) := by
  have h:=(local4 B w).focus slots4 injective4 (fun _=>0) (bank3 B w)
  have hz : dockH slots4 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots4 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input4_join B w))).congr hz rfl
def joined4 := Composition.machine joined3 phase4
def budget4 (B w : Nat) := budget3 B w+1+cost4 B w
theorem run4 (B w : Nat) : Step joined4 (budget4 B w) (fun _=>0) (input B w) (fun _=>0) (bank4 B w) :=
  (run3 B w).seq (step4 B w)

end
end Theorem25Completion.CyclePaletteReserve
