import Proof.Packets.CyclePaletteReserveArithmetic

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

def input (B w : Nat) (i : Fin 80) : List Bool :=
  if i=0 then UnaryTemplate.tape B else if i=1 then UnaryTemplate.tape w else []
-- BEGIN GENERATED WIRING

def slots1 : Fin 3→Fin 80 := ![0,2,3]
theorem injective1 : Function.Injective slots1 := by decide
def phase1 := RecoveryFocus.machine slots1 worker1
def bank1 (B w : Nat) := install slots1 (input B w) (output1 B w)
theorem bank1_slot (B w : Nat) (j : Fin 3) : bank1 B w (slots1 j)=output1 B w j :=
  install_slot slots1 injective1 _ _ j
theorem bank1_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots1 j≠i) : bank1 B w i=input B w i :=
  install_other slots1 _ _ _ hi

theorem input1_join (B w : Nat) : ∀ j,input B w (slots1 j)=input1 B w j := by
  intro j
  fin_cases j
  · change input B w 0=input1 B w 0
    exact (CycleLiveSuccessor.source_eq B).symm
  · change input B w 2=input1 B w 1
    rfl
  · change input B w 3=input1 B w 2
    rfl
theorem step1 (B w : Nat) : Step phase1 (cost1 B w) (fun _=>0) (input B w)
    (fun _=>0) (bank1 B w) := by
  have h:=(local1 B w).focus slots1 injective1 (fun _=>0) (input B w)
  have hz : dockH slots1 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots1 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input1_join B w))).congr hz rfl
def joined1 := phase1
def budget1 (B w : Nat) := cost1 B w
theorem run1 (B w : Nat) : Step joined1 (budget1 B w) (fun _=>0) (input B w) (fun _=>0) (bank1 B w) := step1 B w

end
end Theorem25Completion.CyclePaletteReserve
