import Proof.Packets.CyclePaletteReserveStage6

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

attribute [local irreducible] List.replicate Nat.pow

def slots7 : Fin 4→Fin 80 := ![46,72,76,77]
theorem injective7 : Function.Injective slots7 := by decide
def phase7 := RecoveryFocus.machine slots7 worker7
def bank7 (B w : Nat) := install slots7 (bank6 B w) (output7 B w)
theorem bank7_slot (B w : Nat) (j : Fin 4) : bank7 B w (slots7 j)=output7 B w j :=
  install_slot slots7 injective7 _ _ j
theorem bank7_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots7 j≠i) : bank7 B w i=bank6 B w i :=
  install_other slots7 _ _ _ hi

theorem input7_join (B w : Nat) : ∀ j,bank6 B w (slots7 j)=input7 B w j := by
  intro j
  fin_cases j
  · change bank6 B w 46=input7 B w 0
    rw [bank6_other B w 46 (by decide)]
    rw [bank5_other B w 46 (by decide)]
    rw [bank4_other B w 46 (by decide)]
    change bank3 B w (slots3 41)=_
    rw [bank3_slot]
    exact output3_value B w
  · change bank6 B w 72=input7 B w 1
    change bank6 B w (slots6 13)=_
    rw [bank6_slot]
    exact output6_template B w
  · change bank6 B w 76=input7 B w 2
    rw [bank6_other B w 76 (by decide)]
    rw [bank5_other B w 76 (by decide)]
    rw [bank4_other B w 76 (by decide)]
    rw [bank3_other B w 76 (by decide)]
    rw [bank2_other B w 76 (by decide)]
    rw [bank1_other B w 76 (by decide)]
    rfl
  · change bank6 B w 77=input7 B w 3
    rw [bank6_other B w 77 (by decide)]
    rw [bank5_other B w 77 (by decide)]
    rw [bank4_other B w 77 (by decide)]
    rw [bank3_other B w 77 (by decide)]
    rw [bank2_other B w 77 (by decide)]
    rw [bank1_other B w 77 (by decide)]
    rfl
theorem step7 (B w : Nat) : Step phase7 (cost7 B w) (fun _=>0) (bank6 B w)
    (fun _=>0) (bank7 B w) := by
  have h:=(local7 B w).focus slots7 injective7 (fun _=>0) (bank6 B w)
  have hz : dockH slots7 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots7 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input7_join B w))).congr hz rfl
def joined7 := Composition.machine joined6 phase7
def budget7 (B w : Nat) := budget6 B w+1+cost7 B w
theorem run7 (B w : Nat) : Step joined7 (budget7 B w) (fun _=>0) (input B w) (fun _=>0) (bank7 B w) :=
  (run6 B w).seq (step7 B w)

end
end Theorem25Completion.CyclePaletteReserve
