import Proof.Packets.CyclePaletteReserveStage8

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

attribute [local irreducible] List.replicate Nat.pow

abbrev machine := joined8
abbrev budget := budget8
abbrev output := bank8

abbrev run := run8

theorem template_output_raw (n : Nat) : DimensionTemplate.output false n 0=List.replicate n true := rfl

theorem raw_reserve (B w : Nat) : output B w 76=List.replicate (reserve B w) true :=
  (bank8_slot B w 0).trans (template_output_raw (reserve B w))

end
end Theorem25Completion.CyclePaletteReserve
