import Proof.Packets.UnaryAffine
import Proof.Packets.CycleLiveSuccessor
import Proof.CaseAnalysis.CapacityPower

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section

def reserve (B w : Nat) := 2^102*(B+1)^20*2^(40*w)
def exponent (w : Nat) := 40*w+102

theorem value_eq (B w : Nat) : (B+1)^20*2^exponent w=reserve B w := by
  unfold exponent reserve
  rw [pow_add]
  norm_num
  ring

theorem of_clock {t st n : Nat} {p : Machine t st} {A B : Fin t→List Bool}
    (h : ClockJoin.ReadyRun p n A B) : Step p n (fun _=>0) A (fun _=>0) B := by
  obtain ⟨r,hr,ht,hh,hs⟩ := h
  exact ⟨r,hr,funext hh,ht,hs⟩

def input1 (B _w : Nat) := UWalkUnary.input (B+2) B
def output1 (B _w : Nat) := UWalkUnary.result false true (B+2) B
def worker1 := UWalkUnary.machine false true
def cost1 (B _w : Nat) := 2*B+6
theorem local1 (B w : Nat) : Step worker1 (cost1 B w)
    (fun _=>0) (input1 B w) (fun _=>0) (output1 B w) :=
  of_clock (UWalkUnary.ready false true (B+2) B)

def input2 (B _w : Nat) := DimensionTemplate.input (B+1)
def output2 (B _w : Nat) := DimensionTemplate.output false (B+1)
def worker2 := DimensionTemplate.machine false
def cost2 (B _w : Nat) := 2*(B+1)+8
theorem local2 (B w : Nat) : Step worker2 (cost2 B w)
    (fun _=>0) (input2 B w) (fun _=>0) (output2 B w) :=
  of_clock (DimensionTemplate.ready false (B+1))

def input3 (B _w : Nat) : Fin 43→List Bool := DimensionPower.input 20 (B+1)
def output3 (B _w : Nat) : Fin 43→List Bool := Classical.choose (DimensionPower.power_run 20 1 (B+1))
def worker3 := DimensionPower.machine 20 1
def cost3 (B _w : Nat) := DimensionPower.cost 1 (B+1) 20
theorem local3 (B w : Nat) : Step worker3 (cost3 B w)
    (fun _=>0) (input3 B w) (fun _=>0) (output3 B w) :=
  of_clock (Classical.choose_spec (DimensionPower.power_run 20 1 (B+1))).1
theorem output3_value (B w : Nat) : output3 B w 41=List.replicate ((B+1)^20) true := by
  have hi : DimensionPower.valueSlot 20 20 (by omega)=(41 : Fin 43) := by decide
  have h := (Classical.choose_spec (DimensionPower.power_run 20 1 (B+1))).2.2
  exact (congrArg (output3 B w) hi.symm).trans
    (h.trans (congrArg (fun n=>List.replicate n true) (Nat.one_mul _)))

def input4 (_B w : Nat) := UWalkUnary.input (w+2) w
def output4 (_B w : Nat) := UWalkUnary.result false false (w+2) w
def worker4 := UWalkUnary.machine false false
def cost4 (_B w : Nat) := 2*w+6
theorem local4 (B w : Nat) : Step worker4 (cost4 B w)
    (fun _=>0) (input4 B w) (fun _=>0) (output4 B w) :=
  of_clock (UWalkUnary.ready false false (w+2) w)

def input5 (_B w : Nat) := UnaryAffine.input w
def output5 (_B w : Nat) := Classical.choose (UnaryAffine.run w 40 102)
def worker5 := UnaryAffine.machine 40 102
def cost5 (_B w : Nat) := UnaryAffine.budget w 40 102
theorem local5 (B w : Nat) : Step worker5 (cost5 B w)
    (fun _=>0) (input5 B w) (fun _=>0) (output5 B w) :=
  (Classical.choose_spec (UnaryAffine.run w 40 102)).1
theorem output5_value (B w : Nat) : output5 B w 9=List.replicate (exponent w) true :=
  (Classical.choose_spec (UnaryAffine.run w 40 102)).2.2

def input6 (_B w : Nat) := CloseoutCapacity.Power.input (exponent w)
def output6 (_B w : Nat) := Classical.choose (CloseoutCapacity.Power.power_run (exponent w))
def worker6 := CloseoutCapacity.Power.machine
def cost6 (_B w : Nat) := CloseoutCapacity.Power.budget (exponent w)
theorem local6 (B w : Nat) : Step worker6 (cost6 B w)
    (fun _=>0) (input6 B w) (fun _=>0) (output6 B w) :=
  of_clock (Classical.choose_spec (CloseoutCapacity.Power.power_run (exponent w))).1
theorem output6_template (B w : Nat) : output6 B w 13=UnaryTemplate.tape (2^exponent w) :=
  (Classical.choose_spec (CloseoutCapacity.Power.power_run (exponent w))).2.2

def input7 (B w : Nat) := WilliamsUnaryProduct.input ((B+1)^20) (2^exponent w)
def output7 (B w : Nat) := WilliamsUnaryProduct.output ((B+1)^20) (2^exponent w)
def worker7 := ClockUnaryProduct.machine
def cost7 (B w : Nat) := WilliamsUnaryProduct.budget ((B+1)^20) (2^exponent w)
theorem local7 (B w : Nat) : Step worker7 (cost7 B w)
    (fun _=>0) (input7 B w) (fun _=>0) (output7 B w) := by
  obtain ⟨r,hr,ht,hh,hs⟩:=WilliamsUnaryProduct.product_ready ((B+1)^20) (2^exponent w)
  exact ⟨r,hr,funext hh,ht,hs.le⟩

def input8 (B w : Nat) := DimensionTemplate.input (reserve B w)
def output8 (B w : Nat) := DimensionTemplate.output false (reserve B w)
def worker8 := DimensionTemplate.machine false
def cost8 (B w : Nat) := 2*reserve B w+8
theorem local8 (B w : Nat) : Step worker8 (cost8 B w)
    (fun _=>0) (input8 B w) (fun _=>0) (output8 B w) :=
  of_clock (DimensionTemplate.ready false (reserve B w))

end
end Theorem25Completion.CyclePaletteReserve
