import Proof.Packets.CyclePaletteReserveStage5

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

def slots6 : Fin 17→Fin 80 := ![58,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75]
theorem injective6 : Function.Injective slots6 := by decide
def phase6 := RecoveryFocus.machine slots6 worker6
def bank6 (B w : Nat) := install slots6 (bank5 B w) (output6 B w)
theorem bank6_slot (B w : Nat) (j : Fin 17) : bank6 B w (slots6 j)=output6 B w j :=
  install_slot slots6 injective6 _ _ j
theorem bank6_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots6 j≠i) : bank6 B w i=bank5 B w i :=
  install_other slots6 _ _ _ hi

theorem input6_join (B w : Nat) : ∀ j,bank5 B w (slots6 j)=input6 B w j := by
  intro j
  fin_cases j
  · change bank5 B w 58=input6 B w 0
    change bank5 B w (slots5 9)=_
    rw [bank5_slot]
    exact output5_value B w
  · change bank5 B w 60=input6 B w 1
    rw [bank5_other B w 60 (by decide)]
    rw [bank4_other B w 60 (by decide)]
    rw [bank3_other B w 60 (by decide)]
    rw [bank2_other B w 60 (by decide)]
    rw [bank1_other B w 60 (by decide)]
    rfl
  · change bank5 B w 61=input6 B w 2
    rw [bank5_other B w 61 (by decide)]
    rw [bank4_other B w 61 (by decide)]
    rw [bank3_other B w 61 (by decide)]
    rw [bank2_other B w 61 (by decide)]
    rw [bank1_other B w 61 (by decide)]
    rfl
  · change bank5 B w 62=input6 B w 3
    rw [bank5_other B w 62 (by decide)]
    rw [bank4_other B w 62 (by decide)]
    rw [bank3_other B w 62 (by decide)]
    rw [bank2_other B w 62 (by decide)]
    rw [bank1_other B w 62 (by decide)]
    rfl
  · change bank5 B w 63=input6 B w 4
    rw [bank5_other B w 63 (by decide)]
    rw [bank4_other B w 63 (by decide)]
    rw [bank3_other B w 63 (by decide)]
    rw [bank2_other B w 63 (by decide)]
    rw [bank1_other B w 63 (by decide)]
    rfl
  · change bank5 B w 64=input6 B w 5
    rw [bank5_other B w 64 (by decide)]
    rw [bank4_other B w 64 (by decide)]
    rw [bank3_other B w 64 (by decide)]
    rw [bank2_other B w 64 (by decide)]
    rw [bank1_other B w 64 (by decide)]
    rfl
  · change bank5 B w 65=input6 B w 6
    rw [bank5_other B w 65 (by decide)]
    rw [bank4_other B w 65 (by decide)]
    rw [bank3_other B w 65 (by decide)]
    rw [bank2_other B w 65 (by decide)]
    rw [bank1_other B w 65 (by decide)]
    rfl
  · change bank5 B w 66=input6 B w 7
    rw [bank5_other B w 66 (by decide)]
    rw [bank4_other B w 66 (by decide)]
    rw [bank3_other B w 66 (by decide)]
    rw [bank2_other B w 66 (by decide)]
    rw [bank1_other B w 66 (by decide)]
    rfl
  · change bank5 B w 67=input6 B w 8
    rw [bank5_other B w 67 (by decide)]
    rw [bank4_other B w 67 (by decide)]
    rw [bank3_other B w 67 (by decide)]
    rw [bank2_other B w 67 (by decide)]
    rw [bank1_other B w 67 (by decide)]
    rfl
  · change bank5 B w 68=input6 B w 9
    rw [bank5_other B w 68 (by decide)]
    rw [bank4_other B w 68 (by decide)]
    rw [bank3_other B w 68 (by decide)]
    rw [bank2_other B w 68 (by decide)]
    rw [bank1_other B w 68 (by decide)]
    rfl
  · change bank5 B w 69=input6 B w 10
    rw [bank5_other B w 69 (by decide)]
    rw [bank4_other B w 69 (by decide)]
    rw [bank3_other B w 69 (by decide)]
    rw [bank2_other B w 69 (by decide)]
    rw [bank1_other B w 69 (by decide)]
    rfl
  · change bank5 B w 70=input6 B w 11
    rw [bank5_other B w 70 (by decide)]
    rw [bank4_other B w 70 (by decide)]
    rw [bank3_other B w 70 (by decide)]
    rw [bank2_other B w 70 (by decide)]
    rw [bank1_other B w 70 (by decide)]
    rfl
  · change bank5 B w 71=input6 B w 12
    rw [bank5_other B w 71 (by decide)]
    rw [bank4_other B w 71 (by decide)]
    rw [bank3_other B w 71 (by decide)]
    rw [bank2_other B w 71 (by decide)]
    rw [bank1_other B w 71 (by decide)]
    rfl
  · change bank5 B w 72=input6 B w 13
    rw [bank5_other B w 72 (by decide)]
    rw [bank4_other B w 72 (by decide)]
    rw [bank3_other B w 72 (by decide)]
    rw [bank2_other B w 72 (by decide)]
    rw [bank1_other B w 72 (by decide)]
    rfl
  · change bank5 B w 73=input6 B w 14
    rw [bank5_other B w 73 (by decide)]
    rw [bank4_other B w 73 (by decide)]
    rw [bank3_other B w 73 (by decide)]
    rw [bank2_other B w 73 (by decide)]
    rw [bank1_other B w 73 (by decide)]
    rfl
  · change bank5 B w 74=input6 B w 15
    rw [bank5_other B w 74 (by decide)]
    rw [bank4_other B w 74 (by decide)]
    rw [bank3_other B w 74 (by decide)]
    rw [bank2_other B w 74 (by decide)]
    rw [bank1_other B w 74 (by decide)]
    rfl
  · change bank5 B w 75=input6 B w 16
    rw [bank5_other B w 75 (by decide)]
    rw [bank4_other B w 75 (by decide)]
    rw [bank3_other B w 75 (by decide)]
    rw [bank2_other B w 75 (by decide)]
    rw [bank1_other B w 75 (by decide)]
    rfl
theorem step6 (B w : Nat) : Step phase6 (cost6 B w) (fun _=>0) (bank5 B w)
    (fun _=>0) (bank6 B w) := by
  have h:=(local6 B w).focus slots6 injective6 (fun _=>0) (bank5 B w)
  have hz : dockH slots6 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots6 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input6_join B w))).congr hz rfl
def joined6 := Composition.machine joined5 phase6
def budget6 (B w : Nat) := budget5 B w+1+cost6 B w
theorem run6 (B w : Nat) : Step joined6 (budget6 B w) (fun _=>0) (input B w) (fun _=>0) (bank6 B w) :=
  (run5 B w).seq (step6 B w)

end
end Theorem25Completion.CyclePaletteReserve
