import Proof.Packets.CyclePaletteReserveStage4

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

def slots5 : Fin 11→Fin 80 := ![48,50,51,52,53,54,55,56,57,58,59]
theorem injective5 : Function.Injective slots5 := by decide
def phase5 := RecoveryFocus.machine slots5 worker5
def bank5 (B w : Nat) := install slots5 (bank4 B w) (output5 B w)
theorem bank5_slot (B w : Nat) (j : Fin 11) : bank5 B w (slots5 j)=output5 B w j :=
  install_slot slots5 injective5 _ _ j
theorem bank5_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots5 j≠i) : bank5 B w i=bank4 B w i :=
  install_other slots5 _ _ _ hi

theorem input5_join (B w : Nat) : ∀ j,bank4 B w (slots5 j)=input5 B w j := by
  intro j
  fin_cases j
  · change bank4 B w 48=input5 B w 0
    change bank4 B w (slots4 1)=_
    rw [bank4_slot]
    simp [output4,input5,UWalkUnary.result,UWalkUnary.output,UWalkUnary.lead,UnaryAffine.input]
  · change bank4 B w 50=input5 B w 1
    rw [bank4_other B w 50 (by decide)]
    rw [bank3_other B w 50 (by decide)]
    rw [bank2_other B w 50 (by decide)]
    rw [bank1_other B w 50 (by decide)]
    rfl
  · change bank4 B w 51=input5 B w 2
    rw [bank4_other B w 51 (by decide)]
    rw [bank3_other B w 51 (by decide)]
    rw [bank2_other B w 51 (by decide)]
    rw [bank1_other B w 51 (by decide)]
    rfl
  · change bank4 B w 52=input5 B w 3
    rw [bank4_other B w 52 (by decide)]
    rw [bank3_other B w 52 (by decide)]
    rw [bank2_other B w 52 (by decide)]
    rw [bank1_other B w 52 (by decide)]
    rfl
  · change bank4 B w 53=input5 B w 4
    rw [bank4_other B w 53 (by decide)]
    rw [bank3_other B w 53 (by decide)]
    rw [bank2_other B w 53 (by decide)]
    rw [bank1_other B w 53 (by decide)]
    rfl
  · change bank4 B w 54=input5 B w 5
    rw [bank4_other B w 54 (by decide)]
    rw [bank3_other B w 54 (by decide)]
    rw [bank2_other B w 54 (by decide)]
    rw [bank1_other B w 54 (by decide)]
    rfl
  · change bank4 B w 55=input5 B w 6
    rw [bank4_other B w 55 (by decide)]
    rw [bank3_other B w 55 (by decide)]
    rw [bank2_other B w 55 (by decide)]
    rw [bank1_other B w 55 (by decide)]
    rfl
  · change bank4 B w 56=input5 B w 7
    rw [bank4_other B w 56 (by decide)]
    rw [bank3_other B w 56 (by decide)]
    rw [bank2_other B w 56 (by decide)]
    rw [bank1_other B w 56 (by decide)]
    rfl
  · change bank4 B w 57=input5 B w 8
    rw [bank4_other B w 57 (by decide)]
    rw [bank3_other B w 57 (by decide)]
    rw [bank2_other B w 57 (by decide)]
    rw [bank1_other B w 57 (by decide)]
    rfl
  · change bank4 B w 58=input5 B w 9
    rw [bank4_other B w 58 (by decide)]
    rw [bank3_other B w 58 (by decide)]
    rw [bank2_other B w 58 (by decide)]
    rw [bank1_other B w 58 (by decide)]
    rfl
  · change bank4 B w 59=input5 B w 10
    rw [bank4_other B w 59 (by decide)]
    rw [bank3_other B w 59 (by decide)]
    rw [bank2_other B w 59 (by decide)]
    rw [bank1_other B w 59 (by decide)]
    rfl
theorem step5 (B w : Nat) : Step phase5 (cost5 B w) (fun _=>0) (bank4 B w)
    (fun _=>0) (bank5 B w) := by
  have h:=(local5 B w).focus slots5 injective5 (fun _=>0) (bank4 B w)
  have hz : dockH slots5 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots5 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input5_join B w))).congr hz rfl
def joined5 := Composition.machine joined4 phase5
def budget5 (B w : Nat) := budget4 B w+1+cost5 B w
theorem run5 (B w : Nat) : Step joined5 (budget5 B w) (fun _=>0) (input B w) (fun _=>0) (bank5 B w) :=
  (run4 B w).seq (step5 B w)

end
end Theorem25Completion.CyclePaletteReserve
