import Proof.Packets.CyclePaletteReserveStage2

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

def slots3 (j : Fin 43) : Fin 80 :=
  if j.val=0 then 4 else ⟨j.val+5,by omega⟩
theorem injective3 : Function.Injective slots3 := by
  intro i j he
  apply Fin.ext
  have hv:=congrArg (fun z : Fin 80=>z.val) he
  have value (k : Fin 43) : (slots3 k).val=(if k.val=0 then 4 else k.val+5) := by
    unfold slots3
    split <;>rfl
  rw [value i,value j] at hv
  split_ifs at hv <;> omega

def phase3 := RecoveryFocus.machine slots3 worker3
def bank3 (B w : Nat) := install slots3 (bank2 B w) (output3 B w)
theorem bank3_slot (B w : Nat) (j : Fin 43) : bank3 B w (slots3 j)=output3 B w j :=
  install_slot slots3 injective3 _ _ j
theorem bank3_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots3 j≠i) : bank3 B w i=bank2 B w i :=
  install_other slots3 _ _ _ hi

theorem input3_join (B w : Nat) : ∀ j,bank2 B w (slots3 j)=input3 B w j := by
  intro j
  fin_cases j
  · change bank2 B w 4=input3 B w 0
    change bank2 B w (slots2 1)=_
    rw [bank2_slot]
    rfl
  · change bank2 B w 6=input3 B w 1
    rw [bank2_other B w 6 (by decide)]
    rw [bank1_other B w 6 (by decide)]
    rfl
  · change bank2 B w 7=input3 B w 2
    rw [bank2_other B w 7 (by decide)]
    rw [bank1_other B w 7 (by decide)]
    rfl
  · change bank2 B w 8=input3 B w 3
    rw [bank2_other B w 8 (by decide)]
    rw [bank1_other B w 8 (by decide)]
    rfl
  · change bank2 B w 9=input3 B w 4
    rw [bank2_other B w 9 (by decide)]
    rw [bank1_other B w 9 (by decide)]
    rfl
  · change bank2 B w 10=input3 B w 5
    rw [bank2_other B w 10 (by decide)]
    rw [bank1_other B w 10 (by decide)]
    rfl
  · change bank2 B w 11=input3 B w 6
    rw [bank2_other B w 11 (by decide)]
    rw [bank1_other B w 11 (by decide)]
    rfl
  · change bank2 B w 12=input3 B w 7
    rw [bank2_other B w 12 (by decide)]
    rw [bank1_other B w 12 (by decide)]
    rfl
  · change bank2 B w 13=input3 B w 8
    rw [bank2_other B w 13 (by decide)]
    rw [bank1_other B w 13 (by decide)]
    rfl
  · change bank2 B w 14=input3 B w 9
    rw [bank2_other B w 14 (by decide)]
    rw [bank1_other B w 14 (by decide)]
    rfl
  · change bank2 B w 15=input3 B w 10
    rw [bank2_other B w 15 (by decide)]
    rw [bank1_other B w 15 (by decide)]
    rfl
  · change bank2 B w 16=input3 B w 11
    rw [bank2_other B w 16 (by decide)]
    rw [bank1_other B w 16 (by decide)]
    rfl
  · change bank2 B w 17=input3 B w 12
    rw [bank2_other B w 17 (by decide)]
    rw [bank1_other B w 17 (by decide)]
    rfl
  · change bank2 B w 18=input3 B w 13
    rw [bank2_other B w 18 (by decide)]
    rw [bank1_other B w 18 (by decide)]
    rfl
  · change bank2 B w 19=input3 B w 14
    rw [bank2_other B w 19 (by decide)]
    rw [bank1_other B w 19 (by decide)]
    rfl
  · change bank2 B w 20=input3 B w 15
    rw [bank2_other B w 20 (by decide)]
    rw [bank1_other B w 20 (by decide)]
    rfl
  · change bank2 B w 21=input3 B w 16
    rw [bank2_other B w 21 (by decide)]
    rw [bank1_other B w 21 (by decide)]
    rfl
  · change bank2 B w 22=input3 B w 17
    rw [bank2_other B w 22 (by decide)]
    rw [bank1_other B w 22 (by decide)]
    rfl
  · change bank2 B w 23=input3 B w 18
    rw [bank2_other B w 23 (by decide)]
    rw [bank1_other B w 23 (by decide)]
    rfl
  · change bank2 B w 24=input3 B w 19
    rw [bank2_other B w 24 (by decide)]
    rw [bank1_other B w 24 (by decide)]
    rfl
  · change bank2 B w 25=input3 B w 20
    rw [bank2_other B w 25 (by decide)]
    rw [bank1_other B w 25 (by decide)]
    rfl
  · change bank2 B w 26=input3 B w 21
    rw [bank2_other B w 26 (by decide)]
    rw [bank1_other B w 26 (by decide)]
    rfl
  · change bank2 B w 27=input3 B w 22
    rw [bank2_other B w 27 (by decide)]
    rw [bank1_other B w 27 (by decide)]
    rfl
  · change bank2 B w 28=input3 B w 23
    rw [bank2_other B w 28 (by decide)]
    rw [bank1_other B w 28 (by decide)]
    rfl
  · change bank2 B w 29=input3 B w 24
    rw [bank2_other B w 29 (by decide)]
    rw [bank1_other B w 29 (by decide)]
    rfl
  · change bank2 B w 30=input3 B w 25
    rw [bank2_other B w 30 (by decide)]
    rw [bank1_other B w 30 (by decide)]
    rfl
  · change bank2 B w 31=input3 B w 26
    rw [bank2_other B w 31 (by decide)]
    rw [bank1_other B w 31 (by decide)]
    rfl
  · change bank2 B w 32=input3 B w 27
    rw [bank2_other B w 32 (by decide)]
    rw [bank1_other B w 32 (by decide)]
    rfl
  · change bank2 B w 33=input3 B w 28
    rw [bank2_other B w 33 (by decide)]
    rw [bank1_other B w 33 (by decide)]
    rfl
  · change bank2 B w 34=input3 B w 29
    rw [bank2_other B w 34 (by decide)]
    rw [bank1_other B w 34 (by decide)]
    rfl
  · change bank2 B w 35=input3 B w 30
    rw [bank2_other B w 35 (by decide)]
    rw [bank1_other B w 35 (by decide)]
    rfl
  · change bank2 B w 36=input3 B w 31
    rw [bank2_other B w 36 (by decide)]
    rw [bank1_other B w 36 (by decide)]
    rfl
  · change bank2 B w 37=input3 B w 32
    rw [bank2_other B w 37 (by decide)]
    rw [bank1_other B w 37 (by decide)]
    rfl
  · change bank2 B w 38=input3 B w 33
    rw [bank2_other B w 38 (by decide)]
    rw [bank1_other B w 38 (by decide)]
    rfl
  · change bank2 B w 39=input3 B w 34
    rw [bank2_other B w 39 (by decide)]
    rw [bank1_other B w 39 (by decide)]
    rfl
  · change bank2 B w 40=input3 B w 35
    rw [bank2_other B w 40 (by decide)]
    rw [bank1_other B w 40 (by decide)]
    rfl
  · change bank2 B w 41=input3 B w 36
    rw [bank2_other B w 41 (by decide)]
    rw [bank1_other B w 41 (by decide)]
    rfl
  · change bank2 B w 42=input3 B w 37
    rw [bank2_other B w 42 (by decide)]
    rw [bank1_other B w 42 (by decide)]
    rfl
  · change bank2 B w 43=input3 B w 38
    rw [bank2_other B w 43 (by decide)]
    rw [bank1_other B w 43 (by decide)]
    rfl
  · change bank2 B w 44=input3 B w 39
    rw [bank2_other B w 44 (by decide)]
    rw [bank1_other B w 44 (by decide)]
    rfl
  · change bank2 B w 45=input3 B w 40
    rw [bank2_other B w 45 (by decide)]
    rw [bank1_other B w 45 (by decide)]
    rfl
  · change bank2 B w 46=input3 B w 41
    rw [bank2_other B w 46 (by decide)]
    rw [bank1_other B w 46 (by decide)]
    rfl
  · change bank2 B w 47=input3 B w 42
    rw [bank2_other B w 47 (by decide)]
    rw [bank1_other B w 47 (by decide)]
    rfl
theorem step3 (B w : Nat) : Step phase3 (cost3 B w) (fun _=>0) (bank2 B w)
    (fun _=>0) (bank3 B w) := by
  have h:=(local3 B w).focus slots3 injective3 (fun _=>0) (bank2 B w)
  have hz : dockH slots3 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots3 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input3_join B w))).congr hz rfl
def joined3 := Composition.machine joined2 phase3
def budget3 (B w : Nat) := budget2 B w+1+cost3 B w
theorem run3 (B w : Nat) : Step joined3 (budget3 B w) (fun _=>0) (input B w) (fun _=>0) (bank3 B w) :=
  (run2 B w).seq (step3 B w)

end
end Theorem25Completion.CyclePaletteReserve
