import Proof.Packets.CyclePaletteReserveStage7

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

attribute [local irreducible] List.replicate Nat.pow

def slots8 : Fin 3→Fin 80 := ![76,78,79]
theorem injective8 : Function.Injective slots8 := by decide
def phase8 := RecoveryFocus.machine slots8 worker8
def bank8 (B w : Nat) := install slots8 (bank7 B w) (output8 B w)
theorem bank8_slot (B w : Nat) (j : Fin 3) : bank8 B w (slots8 j)=output8 B w j :=
  install_slot slots8 injective8 _ _ j

theorem product_raw_to_template (a b c : Nat) (h : a*b=c) :
    WilliamsUnaryProduct.output a b 2=DimensionTemplate.input c 0 :=
  congrArg (fun n=>List.replicate n true) h

theorem input8_join_zero (B w : Nat) : bank7 B w (slots8 0)=input8 B w 0 :=
  (bank7_slot B w 2).trans
    (product_raw_to_template ((B+1)^20) (2^exponent w) (reserve B w) (value_eq B w))

theorem input8_join_one (B w : Nat) : bank7 B w (slots8 1)=input8 B w 1 := by
  change bank7 B w 78=input8 B w 1
  rw [bank7_other B w 78 (by decide),bank6_other B w 78 (by decide),
    bank5_other B w 78 (by decide),bank4_other B w 78 (by decide),
    bank3_other B w 78 (by decide),bank2_other B w 78 (by decide),bank1_other B w 78 (by decide)]
  rfl

theorem input8_join_two (B w : Nat) : bank7 B w (slots8 2)=input8 B w 2 := by
  change bank7 B w 79=input8 B w 2
  rw [bank7_other B w 79 (by decide),bank6_other B w 79 (by decide),
    bank5_other B w 79 (by decide),bank4_other B w 79 (by decide),
    bank3_other B w 79 (by decide),bank2_other B w 79 (by decide),bank1_other B w 79 (by decide)]
  rfl

theorem input8_join (B w : Nat) : ∀ j,bank7 B w (slots8 j)=input8 B w j := by
  intro j;fin_cases j
  · exact input8_join_zero B w
  · exact input8_join_one B w
  · exact input8_join_two B w
theorem step8 (B w : Nat) : Step phase8 (cost8 B w) (fun _=>0) (bank7 B w)
    (fun _=>0) (bank8 B w) := by
  have h:=(local8 B w).focus slots8 injective8 (fun _=>0) (bank7 B w)
  have hz : dockH slots8 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots8 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input8_join B w))).congr hz rfl
def joined8 := Composition.machine joined7 phase8
def budget8 (B w : Nat) := budget7 B w+1+cost8 B w
theorem run8 (B w : Nat) : Step joined8 (budget8 B w) (fun _=>0) (input B w) (fun _=>0) (bank8 B w) :=
  (run7 B w).seq (step8 B w)

end
end Theorem25Completion.CyclePaletteReserve
