import Proof.Packets.CyclePaletteReserveStage1

/-! A fixed 80-tape program physically generates the shared reset reserve
2^102*(B+1)^20*2^(40*w) from the measured pool and chosen width templates.
The constant 2^102 is generated by paid arithmetic. -/
set_option autoImplicit false
set_option maxHeartbeats 1200000
set_option maxRecDepth 120000
set_option warningAsError true
namespace Theorem25Completion.CyclePaletteReserve
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryRootRound
open NearCubicWires.RepairSource.ProjectionNormalization NearCubicWires.RepairSource
open NearCubicWires.RepairSource.VerifierDecoding
open Completion
noncomputable section
attribute [local irreducible] worker1 worker2 worker3 worker4 worker5 worker6 worker7 worker8

def slots2 : Fin 3→Fin 80 := ![2,4,5]
theorem injective2 : Function.Injective slots2 := by decide
def phase2 := RecoveryFocus.machine slots2 worker2
def bank2 (B w : Nat) := install slots2 (bank1 B w) (output2 B w)
theorem bank2_slot (B w : Nat) (j : Fin 3) : bank2 B w (slots2 j)=output2 B w j :=
  install_slot slots2 injective2 _ _ j
theorem bank2_other (B w : Nat) (i : Fin 80) (hi : ∀ j,slots2 j≠i) : bank2 B w i=bank1 B w i :=
  install_other slots2 _ _ _ hi

theorem input2_join (B w : Nat) : ∀ j,bank1 B w (slots2 j)=input2 B w j := by
  intro j
  fin_cases j
  · change bank1 B w 2=input2 B w 0
    change bank1 B w (slots1 1)=_
    rw [bank1_slot]
    simp [output1,input2,UWalkUnary.result,UWalkUnary.output,UWalkUnary.lead,DimensionTemplate.input]
  · change bank1 B w 4=input2 B w 1
    rw [bank1_other B w 4 (by decide)]
    rfl
  · change bank1 B w 5=input2 B w 2
    rw [bank1_other B w 5 (by decide)]
    rfl
theorem step2 (B w : Nat) : Step phase2 (cost2 B w) (fun _=>0) (bank1 B w)
    (fun _=>0) (bank2 B w) := by
  have h:=(local2 B w).focus slots2 injective2 (fun _=>0) (bank1 B w)
  have hz : dockH slots2 (fun _ : Fin 80=>0) (fun _=>0)=(fun _=>0) := by
    funext i
    unfold dockH
    cases RecoveryFocus.pick slots2 i <;>rfl
  exact (h.congr_in hz (install_existing _ _ _ (input2_join B w))).congr hz rfl
def joined2 := Composition.machine joined1 phase2
def budget2 (B w : Nat) := budget1 B w+1+cost2 B w
theorem run2 (B w : Nat) : Step joined2 (budget2 B w) (fun _=>0) (input B w) (fun _=>0) (bank2 B w) :=
  (run1 B w).seq (step2 B w)

end
end Theorem25Completion.CyclePaletteReserve
