import Proof.MachineModel.ClosureLocalSupport
import Proof.Packets.PhysicalBankCopy
import Proof.Rows.PhysicalFocusBoundary

/-! Reusable normalized arithmetic. The worker runs on a physically padded
bank, its actual result is copied to the right operand, and every private
scratch tape is overwritten before the next call. Capacity words are explicit
physical inputs, generated by the separate reserve producer. -/
set_option autoImplicit false
set_option maxHeartbeats 1400000
set_option maxRecDepth 120000
set_option warningAsError true
set_option linter.unusedSimpArgs false
namespace PCJ9eff70d512234a4c_Fixed.Materializer.ReusableArithmetic
open NearCubicWires NearCubicWires.LocalBitMultitape NearCubicWires.RepairOrdinary
open NearCubicWires.ExtDecompositionBatch NearCubicWires.RepairOrdinary.RecoveryExecution
open NearCubicWires.RepairOrdinary.RecoveryRootRound

def localHeads (i : Fin 30) : Nat := if i=3 ∨ i=13 ∨ i=24 ∨ i=27 ∨ i=28 then 1 else 0
def heads (i : Fin 34) : Nat := if i=31 then 1 else 0
def bank (R : Nat) (a : Fin 30 → List Bool) (i : Fin 34) : List Bool :=
  Fin.addCases a (![List.replicate (R+3) false,UnaryTemplate.tape R,
    List.replicate R true,List.replicate (R+3) false] : Fin 4 → List Bool) i
def padded (R : Nat) (a : Fin 30 → List Bool) (i : Fin 30) : List Bool := ZeroPadding.pad R (a i)

def boot : Machine 30 2 where
  descriptionBits:=0
  start:=0
  halted:=fun q=>q.val==1
  rule:=fun q _=>if q.val=0 then some
    ⟨1,fun _=>none,fun i=>if localHeads i=1 then .right else .stay⟩ else none

theorem boot_step (a : Fin 30 → List Bool) : Step boot 1 (fun _=>0) a localHeads a := by
  have hs : step boot (⟨0,fun _=>0,a⟩ : Configuration 30 2)=some ⟨1,localHeads,a⟩ := by
    simp only [step,boot]
    apply congrArg some
    apply configuration_ext
    · rfl
    · funext i; fin_cases i <;> simp [applyAction,HeadMove.apply,localHeads]
    · rfl
  obtain ⟨r,hr,hf,ht⟩ := (Timed.single (by rfl) hs).run (by rfl)
  exact ⟨r,hr,congrArg Configuration.heads hf,congrArg Configuration.tapes hf,ht.le⟩

noncomputable def worker {s : Nat} (p : Machine 30 s) :=
  TapeEmbedding.machine 3 (MaskedReset.machine (Composition.machine boot p) (fun _=>true))

theorem worker_step {s fuel R : Nat} {p : Machine 30 s}
    {a b : Fin 30 → List Bool} {h : Fin 30 → Nat}
    (hp : Step p fuel localHeads a h b) (hcap : fuel+3≤R) :
    Step (worker p) (2*fuel+6) heads (bank R (padded R a)) heads (bank R (padded R b)) := by
  have first := ((boot_step a).seq hp).pad (fun _=>R)
  have masked := first.mask (fun _=>true) (by intro i _;rfl) (cap:=R+3) (by omega)
  have extended := masked.embed (![1,0,0] : Fin 3 → Nat)
    (![UnaryTemplate.tape R,List.replicate R true,List.replicate (R+3) false] : Fin 3 → List Bool)
  have inputH : (Fin.addCases (m:=31) (n:=3) (motive:=fun _=>Nat)
      (Fin.addCases (m:=30) (n:=1) (motive:=fun _=>Nat) (fun _=>0) (fun _=>0))
      (![1,0,0] : Fin 3 → Nat))=heads := by funext i;fin_cases i <;>rfl
  have bankEq (c : Fin 30 → List Bool) :
      (Fin.addCases (m:=31) (n:=3) (motive:=fun _=>List Bool)
        (Fin.addCases (m:=30) (n:=1) (motive:=fun _=>List Bool) (padded R c)
          (fun _=>List.replicate (R+3) false))
        (![UnaryTemplate.tape R,List.replicate R true,List.replicate (R+3) false] : Fin 3 → List Bool))=
      bank R (padded R c) := by funext i;fin_cases i <;>rfl
  have result := (extended.congr_in inputH (bankEq a)).congr (by simpa using inputH) (bankEq b)
  convert result using 1 <;> first | rfl | omega

theorem output_fits {s fuel R : Nat} {p : Machine 30 s}
    {a b : Fin 30 → List Bool} {h : Fin 30 → Nat}
    (hp : Step p fuel localHeads a h b) (ha : ∀ i,(a i).length≤R) (hcap : fuel+3≤R) :
    ∀ i,(padded R b i).length=R := by
  intro i
  have fit := P1Closure.LocalSupport.step_fits ((boot_step a).seq hp) i R (ha i) (by omega)
  simp only [padded,ZeroPadding.pad_length,Nat.max_eq_left fit]

def copySlots (source target : Fin 30) : Fin 3 → Fin 34 := ![31,source.castAdd 4,target.castAdd 4]
noncomputable def copyMachine (source target : Fin 30) := RecoveryFocus.machine
  (copySlots source target) PhysicalBankCopy.machine
def replaced (a : Fin 30 → List Bool) (source target : Fin 30) := Function.update a target (a source)

theorem copy_step (R : Nat) (a : Fin 30 → List Bool) (source target : Fin 30)
    (hne : source≠target) (hs : (a source).length=R) (ht : (a target).length=R) :
    Step (copyMachine source target) (2*R+2) heads (bank R a)
      heads (bank R (replaced a source target)) := by
  have hi : Function.Injective (copySlots source target) := by
    intro i j h
    have hv := congrArg Fin.val h
    have hn : source.val ≠ target.val := by intro he;exact hne (Fin.ext he)
    fin_cases i <;> fin_cases j <;> try rfl
    all_goals norm_num [copySlots] at hv
    all_goals exfalso;omega
  obtain ⟨r,hr,hf,hn⟩ := PhysicalBankCopy.copy_run (a source) (a target) (ht.trans hs.symm) [] [] [] []
  have small : Step PhysicalBankCopy.machine (2*R+2)
      ![1,0,0] ![UnaryTemplate.tape R,a source,a target]
      ![1,0,0] ![UnaryTemplate.tape R,a source,a source] := by
    rw [hs] at hr hn
    refine ⟨r,?_,?_,?_,hn.le⟩
    · simpa only [PhysicalBankCopy.cfg,List.nil_append,List.append_nil,List.length_nil,Nat.zero_add,hs,PhysicalBankCopy.machine] using hr
    · rw [hf];rfl
    · rw [hf];simp [PhysicalBankCopy.cfg,hs]
  apply PhysicalFocusBoundary.focus small (copySlots source target) hi heads heads (bank R a)
    (bank R (replaced a source target))
  · intro i;fin_cases i <;> simp [heads,copySlots,Fin.castAdd,Fin.ext_iff,show source.val≠31 by omega,show target.val≠31 by omega]
  · intro i;fin_cases i <;> simp [bank,copySlots,Fin.addCases]
  · intro i;fin_cases i <;> simp [heads,copySlots,Fin.castAdd,Fin.ext_iff,show source.val≠31 by omega,show target.val≠31 by omega]
  · intro i;fin_cases i <;> simp [bank,copySlots,Fin.addCases,replaced,Function.update,hne,hne.symm]
  · intro i
    refine Fin.addCases (m:=30) (n:=4) (fun j=>?_) (fun j=>?_) i
    · intro away
      have hj : j≠target := by intro hj;subst j;exact away 2 rfl
      exact ⟨rfl,by simp [bank,replaced,Function.update,hj]⟩
    · intro _
      exact ⟨rfl,by simp only [bank,Fin.addCases_right]⟩

end PCJ9eff70d512234a4c_Fixed.Materializer.ReusableArithmetic
