import Proof.SourceAssembly.SourceLiveCount
import Proof.SourceAssembly.SourceSingletonCounters

set_option autoImplicit false
set_option maxHeartbeats 250000
set_option maxRecDepth 120000
set_option warningAsError true
namespace PCJ6e421fabe2aa4155_SourceSingletonLive
open NearCubicWires LocalBitMultitape ExtDecompositionBatch RepairOrdinary RepairRepresentation
open SourceInterfaces RecoveryRootRound CloseoutRowsEstimatorParity SupplierPipeline SupplierEstimator CompilerSemantics RepairSource.VerifierDecoding
open CloseoutRowsOriginalClause (index negative)
open PCJd4d1d9d7d1fa4313_Production
open PCJ6e421fabe2aa4155_SourceSingletonRequest (request circuit)
noncomputable section




end
end PCJ6e421fabe2aa4155_SourceSingletonLive
