import Proof.Circuits.InverseSelectorCanonicalResourceFrontier
import Proof.Circuits.TotalInverseCanonicalRangeResources

namespace NearCubicWires.TotalInverseCanonicalCompiledBodyResources

open NearCubicWires
open NearCubicWires.BankDispatchedTargetBody
open NearCubicWires.BankEmittedBranchSelector
open NearCubicWires.BankEmittedAtomLoop
open NearCubicWires.BranchTargetLanguageProgram
open NearCubicWires.CaseOneRecoveryAssembly
open NearCubicWires.CaseTwoOccurrenceProgram
open NearCubicWires.ExecutableInterfaces
open NearCubicWires.InverseSelectorCanonicalResourceFrontier
open NearCubicWires.InverseSelectorOccurrenceEncodingClosure
open NearCubicWires.InverseSubstitutionRequestWordClosure
open NearCubicWires.InverseTotalScheduledRowStageClosure
open NearCubicWires.OuterPCPRecovery
open NearCubicWires.PaddedProjectionPresentation
open NearCubicWires.PaddedRunnerBudgetDomination
open NearCubicWires.PolynomialClock
open NearCubicWires.SelectorDrivenAtomContextRuns
open NearCubicWires.SelectorDrivenBodyDispatch
open NearCubicWires.SelectorDrivenRegisterTargetChainBase
open NearCubicWires.TotalBankEmittedAtomLoop
open NearCubicWires.TotalInverseCanonicalCompilerRuns
open NearCubicWires.TotalInverseCanonicalCompiledBodyRun
open NearCubicWires.TotalInverseCanonicalRangeResources
open NearCubicWires.TotalInverseSelectorAtomStreamClosure
open NearCubicWires.TotalInverseSelectorCompiledBody
open NearCubicWires.TotalInverseSelectorDirectBodyClosure
open NearCubicWires.TotalSelectorBodyAdapter
open NearCubicWires.TotalSelectorDrivenEmitterResources
open NearCubicWires.TaggedProgramChoice
open NearCubicWires.UniformTargetTotalRun
open NearCubicWires.ValidatorPolynomialDomination
open NearCubicWires.VerifiedLinker

/-! The six-way range also closes the exact totality consumer outright. -/

end NearCubicWires.TotalInverseCanonicalCompiledBodyResources
