import Proof.MachineModel.OrdinaryMatrixPacketFields

/-! The original-only entry physically copies its request and initializes
the offset. Both retained copy counters are generated by that first copy. -/
namespace NearCubicWires.RepairOrdinary.MatrixPacketColdPrepare
open LocalBitMultitape RecoveryRootRound MatrixScoreBatch RepairRepresentation
set_option autoImplicit false
set_option maxHeartbeats 250000
set_option maxRecDepth 120000
set_option warningAsError true

noncomputable def cold (a : WilliamsAlgorithm) (E : ℕ) (r : Request) : Fin (MatrixPacketRestore.tapes a E) → List Bool :=
  fun i => if i=MatrixPacketRestore.copySlots a E 0 then physicalInput r else []
noncomputable def copied (a : WilliamsAlgorithm) (E : ℕ) (r : Request) :=
  install (MatrixPacketRestore.copySlots a E) (cold a E r) (MatrixPacketRequestCopy.output (word r) 0 0 0)
noncomputable def output (a : WilliamsAlgorithm) (E : ℕ) (r : Request) :=
  install (MatrixPacketStateAdvance.slot a E) (copied a E r) (fun _ => UnaryTemplate.tape 0)
noncomputable def heads (a : WilliamsAlgorithm) (E : ℕ) : Fin (MatrixPacketRestore.tapes a E) → ℕ :=
  fun i => if i=MatrixPacketStateAdvance.slot a E 0 then 1 else 0
noncomputable def first (a : WilliamsAlgorithm) (E : ℕ) :=
  RecoveryFocus.machine (MatrixPacketRestore.copySlots a E) RecoveryRootRound.copyMachine
noncomputable def last (a : WilliamsAlgorithm) (E : ℕ) :=
  RecoveryFocus.machine (MatrixPacketStateAdvance.slot a E) MatrixPacketOffset.init
noncomputable def machine (a : WilliamsAlgorithm) (E : ℕ) := Composition.machine (first a E) (last a E)
def budget (r : Request) := 8*(word r).length+11

theorem cold_copy (a : WilliamsAlgorithm) (E : ℕ) (r : Request) :
    ReadyRun (first a E) (8*(word r).length+8) (cold a E r) (copied a E r) := by
  apply (MatrixPacketRequestCopy.copy_ready (word r) 0 0 0).focus
    (MatrixPacketRestore.copySlots a E) (MatrixPacketRestore.copySlots_injective a E) (cold a E r)
  intro j
  by_cases hj : j=0
  · subst j
    simp [cold,MatrixPacketRequestCopy.input]
    rfl
  · have hn : MatrixPacketRestore.copySlots a E j≠MatrixPacketRestore.copySlots a E 0 :=
      fun he => hj (MatrixPacketRestore.copySlots_injective a E he)
    rw [cold,if_neg hn]
    fin_cases j <;> simp_all [MatrixPacketRequestCopy.input]

theorem copied_offset (a : WilliamsAlgorithm) (E : ℕ) (r : Request) :
    copied a E r (MatrixPacketStateAdvance.slot a E 0)=[] := by
  have hc:=install_other (MatrixPacketRestore.copySlots a E) (cold a E r)
    (MatrixPacketRequestCopy.output (word r) 0 0 0) (MatrixPacketStateAdvance.slot a E 0)
    (MatrixPacketRestoreDock.copy_misses a E (MatrixPacketState.offset a) (by change (424 : ℕ)≠0; decide))
  apply hc.trans
  have hn : MatrixPacketStateAdvance.slot a E 0≠MatrixPacketRestore.copySlots a E 0 :=
    MatrixPacketRestoreControls.controls_outside a E 2 (MatrixPacketState.offset a)
  exact if_neg hn

theorem prepare_run (a : WilliamsAlgorithm) (E : ℕ) (r : Request) : ∃ actual,
    run (machine a E) (budget r) (cold a E r)=some actual ∧
    actual.final.tapes=output a E r ∧ actual.final.heads=heads a E ∧ actual.steps=budget r := by
  obtain ⟨base,hb,bt,bh,bs⟩:=cold_copy a E r
  obtain ⟨init,hi,it,ih,is⟩:=MatrixPacketOffset.init_run
  let entry:=initialConfiguration MatrixPacketOffset.init (fun _ => [])
  have hentry : RecoveryFocus.config (MatrixPacketStateAdvance.slot a E) base.final.heads base.final.tapes entry=
      Composition.restart base.final (last a E).start := by
    apply WilliamsSourceCrop.focus_same
    · intro j
      exact bh _
    · intro j
      exact (congrFun bt _).trans (copied_offset a E r)
  obtain ⟨final,hf,ff,fs⟩:=RecoveryFocus.run_config (MatrixPacketStateAdvance.slot a E)
    (MatrixPacketStateAdvance.slot_injective a E) MatrixPacketOffset.init base.final.heads base.final.tapes
    2 entry init hi
  rw [hentry] at hf
  have whole:=Composition.run_join (first a E) (last a E) _ _ _ base final hb hf
  have hbnd : (8*(word r).length+8)+1+2=budget r := by unfold budget; omega
  rw [hbnd] at whole
  refine ⟨Composition.joinedReceipt base final,whole,?_,?_,?_⟩
  · change final.final.tapes=output a E r
    rw [ff]
    change install (MatrixPacketStateAdvance.slot a E) base.final.tapes init.final.tapes=output a E r
    rw [bt,it]
    rfl
  · change final.final.heads=heads a E
    rw [ff]
    funext i
    by_cases hi : i=MatrixPacketStateAdvance.slot a E 0
    · subst i
      simp only [RecoveryFocus.config,RecoveryFocus.pick_slot (MatrixPacketStateAdvance.slot a E)
        (MatrixPacketStateAdvance.slot_injective a E),ih,heads,if_true]
    · have no : ∀ j,MatrixPacketStateAdvance.slot a E j≠i := by
        intro j he
        exact hi he.symm
      have pk : RecoveryFocus.pick (MatrixPacketStateAdvance.slot a E) i=none := by
        simp only [RecoveryFocus.pick,dif_neg (not_exists.mpr no)]
      simp only [RecoveryFocus.config,pk,heads,if_neg hi]
      exact bh i
  · change base.steps+1+final.steps=budget r
    rw [bs,fs,is]
    exact hbnd

end NearCubicWires.RepairOrdinary.MatrixPacketColdPrepare
