import Proof.MachineModel.OrdinaryMatrixFramedBlock

/-! Calls for counting physical 2*U-bit groups in the retained framed
matrix payload. The count tape is generated by ordinary writes. -/
namespace NearCubicWires.RepairOrdinary.MatrixPayloadCount
open LocalBitMultitape RecoveryExecution
set_option autoImplicit false
set_option maxHeartbeats 250000
set_option maxRecDepth 120000
set_option warningAsError true

def config {s : ℕ} (q : Fin s) (u : ℕ) (source : List Bool) (pos count : ℕ) : Configuration 3 s :=
  ⟨q,![1,pos,count+1],![UnaryTemplate.tape u,source,false::List.replicate count true]⟩
def finished {s : ℕ} (q : Fin s) (u : ℕ) (source : List Bool) (pos count : ℕ) : Configuration 3 s :=
  ⟨q,![1,pos,1],![UnaryTemplate.tape u,source,UnaryTemplate.tape count]⟩
def gate : Machine 3 2 where
  descriptionBits := 0
  start := 0
  halted := fun q => q.val==1
  rule := fun q _ => if q.val=0 then some ⟨1,fun _ => none,fun _ => .stay⟩ else none
def skip : Machine 3 12 := TapeEmbedding.machine 1 MatrixFramedBlock.double
def outSlot : Fin 1 → Fin 3 := fun _ => 2
noncomputable def emit : Machine 3 2 := RecoveryFocus.machine outSlot (MatrixUnaryFinish.append true)
noncomputable def finish : Machine 3 5 := RecoveryFocus.machine outSlot MatrixUnaryFinish.machine

theorem out_pick : ∀ i : Fin 3, RecoveryFocus.pick outSlot i =
    (![none,none,some 0] : Fin 3 → Option (Fin 1)) i := by
  intro i; fin_cases i
  · decide
  · decide
  · exact RecoveryFocus.pick_slot outSlot (by decide) 0

theorem gate_run (u : ℕ) (source : List Bool) (pos count : ℕ) :
    ∃ r : ExecutionReceipt 3 2,
      runFrom gate 1 (config 0 u source pos count)=some r ∧
      r.final=config 1 u source pos count ∧ r.steps=1 := by
  have hs : step gate (config 0 u source pos count)=some (config 1 u source pos count) := by
    simp [step,gate,config]
    apply configuration_ext
    · rfl
    · funext i; fin_cases i <;> simp [applyAction,HeadMove.apply]
    · rfl
  exact (Timed.single (by rfl) hs).run (by rfl)

theorem skip_run (u : ℕ) (source : List Bool) (pos count : ℕ) :
    ∃ r : ExecutionReceipt 3 12,
      runFrom skip (6*u+9) (config 0 u source pos count)=some r ∧
      r.final=config 11 u source (pos+4*u) count ∧ r.steps=6*u+9 := by
  obtain ⟨base,hr,hf,hs⟩ := MatrixFramedBlock.double_run u source pos
  have he := TapeEmbedding.run_embed MatrixFramedBlock.double (fun _ : Fin 1 => count+1)
    (fun _ : Fin 1 => false::List.replicate count true) _ _ base hr
  have place (q : Fin 12) (p : ℕ) : TapeEmbedding.config (fun _ : Fin 1 => count+1)
      (fun _ : Fin 1 => false::List.replicate count true)
      (MatrixFramedBlock.config q u 1 source p)=config q u source p count := by
    apply configuration_ext
    · rfl
    · funext i; fin_cases i <;> rfl
    · funext i; fin_cases i <;> rfl
  rw [place] at he
  refine ⟨TapeEmbedding.receipt (fun _ : Fin 1 => count+1)
    (fun _ : Fin 1 => false::List.replicate count true) base,he,?_,hs⟩
  change TapeEmbedding.config (fun _ : Fin 1 => count+1)
    (fun _ : Fin 1 => false::List.replicate count true) base.final=_
  rw [hf]
  exact place _ _

theorem emit_run (u : ℕ) (source : List Bool) (pos count : ℕ) :
    ∃ r : ExecutionReceipt 3 2,
      runFrom emit 1 (config emit.start u source pos count)=some r ∧
      r.final=config 1 u source pos (count+1) ∧ r.steps=1 := by
  obtain ⟨base,hr,hf,hs⟩ := MatrixUnaryFinish.append_run true (false::List.replicate count true)
  let ambient := config emit.start u source pos count
  let entry := MatrixUnaryFinish.config (s:=2) 0 (false::List.replicate count true) (count+1)
  have hi : RecoveryFocus.config outSlot ambient.heads ambient.tapes entry=ambient := by
    apply WilliamsSourceCrop.focus_same
    · intro i; fin_cases i; rfl
    · intro i; fin_cases i; rfl
  obtain ⟨r,hp,hfinal,hsteps⟩ := RecoveryFocus.run_config outSlot (by decide)
    (MatrixUnaryFinish.append true) ambient.heads ambient.tapes 1 entry base (by simpa [entry] using hr)
  rw [hi] at hp
  refine ⟨r,hp,?_,hsteps.trans hs⟩
  rw [hfinal,hf]
  apply configuration_ext
  · rfl
  · funext i; fin_cases i <;> simp [RecoveryFocus.config,out_pick,config,ambient,MatrixUnaryFinish.config]
  · funext i; fin_cases i <;> simp [RecoveryFocus.config,out_pick,config,ambient,MatrixUnaryFinish.config,List.replicate_add]

theorem finish_run (u : ℕ) (source : List Bool) (pos count : ℕ) :
    ∃ r : ExecutionReceipt 3 5,
      runFrom finish (count+4) (config finish.start u source pos count)=some r ∧
      r.final=finished 4 u source pos count ∧ r.steps=count+4 := by
  obtain ⟨base,hr,hf,hs⟩ := MatrixUnaryFinish.finish_run count
  let ambient := config finish.start u source pos count
  let entry := MatrixUnaryFinish.config (s:=5) 0 (false::List.replicate count true) (count+1)
  have hi : RecoveryFocus.config outSlot ambient.heads ambient.tapes entry=ambient := by
    apply WilliamsSourceCrop.focus_same
    · intro i; fin_cases i; rfl
    · intro i; fin_cases i; rfl
  obtain ⟨r,hp,hfinal,hsteps⟩ := RecoveryFocus.run_config outSlot (by decide)
    MatrixUnaryFinish.machine ambient.heads ambient.tapes (count+4) entry base hr
  rw [hi] at hp
  refine ⟨r,hp,?_,hsteps.trans hs⟩
  rw [hfinal,hf]
  apply configuration_ext
  · rfl
  · funext i; fin_cases i <;> simp [RecoveryFocus.config,out_pick,config,ambient,finished,MatrixUnaryFinish.config]
  · funext i; fin_cases i <;> simp [RecoveryFocus.config,out_pick,config,ambient,finished,MatrixUnaryFinish.config]

end NearCubicWires.RepairOrdinary.MatrixPayloadCount
