import Proof.MachineModel.TopDownPaidBinaryReserves

/-! Substitute explicit common reserves into both actual family consumers.
No storage-capacity hypothesis remains; the displayed source bank is still
an upstream physical production duty. -/
set_option autoImplicit false
set_option maxHeartbeats 250000
set_option maxRecDepth 120000
set_option warningAsError true
namespace NearCubicWires.P1TopDownPaidFamilyReserves
open LocalBitMultitape RepairOrdinary RepairRepresentation ExtDecompositionBatch
open CloseoutRowsEstimator CloseoutRowsEstimatorCoefficients CompetitorSelectedCount
open MatrixScoreBatch CompetitorCountMask RecoveryRootRound P1Closure
open SupplierPipeline SupplierEstimator SupplierPrime SourceInterfaces CanonicalFourfoldRowProgram
open RepairSource CloseoutFinal CloseoutRawRows
open C10ExternalRowLoop C10ThresholdNaturalRowPrint C10ThresholdParityRow
open C10ThresholdEstimateRowJoin CloseoutFinalC10RowAnswerWord
open CloseoutFinalC10SupplierAccuracy (rowAnswer)
open C10ThresholdNaturalSum (nativeNumerator)
open P1TopDownPaidReusable P1TopDownPaidReusableReserves P1TopDownPaidBinaryReserves
attribute [local irreducible] BinaryPool.pool CompactBounds.radix
  symDatum thrDatum familyPolynomial pairList


section Sym

end Sym

section Thr

end Thr

end NearCubicWires.P1TopDownPaidFamilyReserves
